### ISSUE TITLE
[Package Request] - dkms

### ISSUE THREAD

**Issue by aceclan** [amazonlinux/amazon-linux-2022#127] opened 2022-05-25 14:40 UTC
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
dkms - Dynamic Kernel Module Support Framework

**Is this an update to existing package or new package request?**
Is a new package.

**Is this package available in Amazon Linux 2?**
Yes this was available on Amazon Linux 2.

**Comment by ozbenh** [comment] 2022-08-15 22:32
This will show up before GA

**Comment by stewartsmith** [comment] 2022-08-31 21:52
A duplicate of https://github.com/amazonlinux/amazon-linux-2022/issues/77 and both `dkms` and `acpid` are now in the repositories.

**Closed by stewartsmith** 2022-08-31 21:52 UTC
