### ISSUE TITLE
[Package Request] - podman

### ISSUE THREAD

**Issue by osama004** [amazonlinux/amazon-linux-2022#187] opened 2022-09-08 10:12 UTC
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2?**

**Number of users impacted**

**Comment by stewartsmith** [comment] 2022-09-19 15:45
Duplicate of https://github.com/amazonlinux/amazon-linux-2022/issues/67

**Closed by stewartsmith** 2022-09-19 15:45 UTC
